fixup! change secrets stage to a clustersourcetemplate

diff --git a/demos/usn-raise-made-easy/resources/clustertask_secrets.yaml b/demos/usn-raise-made-easy/resources/clustertask_secrets.yaml
--- a/demos/usn-raise-made-easy/resources/clustertask_secrets.yaml
+++ b/demos/usn-raise-made-easy/resources/clustertask_secrets.yaml
@@ -6,8 +6,8 @@ spec:
   description: |-
     Uses Yelp's detect-secrets to scan for commonly-found secrets within source code tracked by a provided Git repository.
   params:
-  - name: git_url
-  - name: git_sha
+  - name: git_blob_url
+  - name: git_blob_ref
   results:
   - name: provided_git_url
   - name: provided_git_ref
@@ -16,29 +16,35 @@ spec:
   - name: scan-result
     description: The result of the ZAP scan.
     type: string
-  workspaces:
-    - name: git_repo
-      mountPath: /repo
   steps:
   # output-repo-properties is needed so that the
-  # ClusterSourceTemplate that calls this task can re-retrieve the URL and ref and feed it down
-  # through the supply chain.
+  # ClusterSourceTemplate that calls this task can re-retrieve the 
   - image: bash:5
-    name: output-repo-url
+    name: output-repo-properties
     script: |
       #!/usr/bin/env bash
-      echo $(params.git_url) > $(results.provided_git_url.path)
+      tr -d '\n' <<< $(params.git_blob_url) > $(results.provided_git_url.path)
+      tr -d '\n' <<< $(params.git_blob_ref) > $(results.provided_git_ref.path)
   - image: bash:5
-    name: output-repo-ref
+    name: detect-secrets
     script: |
       #!/usr/bin/env bash
-      echo $(params.git_ref) > $(results.provided_git_ref.path)
-  - image: bash:5
-    name: clone-the-repository
-    script: |
-      #!/usr/bin/env bash
-      apk add git curl --no-progress -q
-      cd /repo
-      git clone --branch $(params.git_sha) $(params.git_url)
-      ls /repo
+      set -euo pipefail
+      apk add git curl python3 py3-pip jq --no-progress -q
+
+      curl -o /tmp/repo.tar.gz $(params.git_blob_url)
+      mkdir /repo && tar -xzf /tmp/repo.tar.gz -C /repo
+
+
+      # Required to turn off the virtualenv check.
+      pip install detect-secrets --break-system-packages
+      results=$(detect-secrets -C /repo scan --all-files | jq -r .results)
+      if test "$results" == '{}'
+      then
+        >&2 echo "INFO: No secrets detected!"
+        exit 0
+      fi
+      >&2 echo "ERROR: Secrets scan failed! See results below to see where secrets were found."
+      echo "$results"
+      exit 1
 
